#upload to gcs
import upload_to_gcs

reviews = [
    "The hotel is nice, pleasant and comfortable. The rooms are comfortable and clean, the bathrooms functional. One minor -ve was the doors to the lobby of the service elevators were always open and the stink permeated the whole corridor. They need to either keep those doors closed or spray that area down with disinfectant and air freshner.\nWe used the pool one evening and it had some leaves / debris floating about but that's to be expected since its open air... otherwise the pool itself was clean. The pool area however was littered with cigarette butts, discarded towels and empty plastic bottles. We also had to ask for fresh towels and honestly, they weren't the best. The gym is ok. The spa services were fairly average. No complaints but nothing to rave about either. The masseuse needed quite a bit of directions.\n\nThe worst is the food. We ordered dessert from room service one night and had breakfast 2 mornings - both left much to be desired. At breakfast - the french toast was undercooked and soaked in sugar syrup (not maple syrup or honey). They ran out of tea bags. The baked goods were a tad stale. The next morning I got a plain cheese omelette and the cheese tasted rancid. Also their toaster was not working.\n\nGiven the location, price and overall comfort of the rooms, I liked the hotel but I will avoid eating here as much as possible. If you don't care for pool/spa etc and make plans to eat outside, the stay is quite pleasant and worry free.",
    "Excellent place to stay quite a pleasant experience. Great food provided on demand even for small children, clean environment, sanirized rooms felt safe with all protocols. Our family enjoyed a lot, arranged a seperate place to have a get together wit whole family of 22",
    "I am staying in this hotel since long and have received very good support from all departments/staff i.e. Dining, front desk and house keeping.\n\nAll staff is available for help and during pandemic period staff had keep on doing sanitization of floor and rooms.\n\nEspecially thanks to below staff's for their loyal work and sincerity.\n\nDining room - Rima and Panchakshri\nChef trilok & chef sainath\n\nHouse keeping - Renuka\n\nFront desk - Abhishek Pande",
    "This is simply not Lemon Tree Premium type hotel,only by name they are,\nYou have to carry every single things with you, everything is paid here, even water is paid. Its not like you are checking in some 4-5 star category hotel, its like you will feel like some oyo kind hotel, even they are also very clear about the policies.\n\nIf a hotel start doing this kind of cost cutting procedure, where hot water only in morning and evening, you can not handle ur AC cooling, no saving kit, no toothbrush,no soap etc etc then you can imagine that they definitely not washing bedsheets, pilow cover and all timely to save money.\nMany 4-5 Star category hotel we have available in Pune, go there,keep lemon tree your last option",
    "Extremely helpful and friendly staff. They make sure that you have a pleasant and comfortable stay right from the front desk to the housekeeping. The Chef Ruturaj Guruju made special arrangements for my diabetic grandparents by preparing the meals with less oil and no spice, which is appreciated and commendable. Abhishek and other staff members are very welcoming and friendly. My grandmother would like to specially thank Jindani from housekeeping for taking utmost care of their needs during their stay at Lemon Tree Premier, Pune.",
    "The overall experience has been really nice. Rooms are cozy and comfortable. The entire housing keeping staff has also been really helpful especially Renuka who cleaned the room in the morning and was very helpful in every aspect.",
    "I had a conference for 3 days in this property and unfortunately it was the worst experience I had. Staring from set up where the incharge by the name Ravi was not at all helpful. Seems like he was not at all interested in helping us out in anyway. As we needed to chk the setup a day before Mr. Ravi gave a feel that it’s such a small thing so it can be done last moment.\nWe had a negotiation with Me. Vijay who literally was shouting at one of my partner on the 1st day of our conference n was just not listening at all. When my partner raised his voice is when vijay got mellowed down. Lemon tree is so called 4 star but the way they handled the whole thing was lower than a 1 star property. I asked for a water dispenser as bottled water means lot of plastic waste so they provided a plastic transparent container on which they kept a saucer as a lid n they were giving only 20 tea bags for the whole day n over & above that was chargeable as we requested for tea coffee should be kept all the time as people feel sleepy during long sessions.\nFood was also not very great though the chef was very cooperative. Toilets we stinky n mostly never had tissues, hand tissue were never available n hand dryer was never working.",
    "Lemon tree premier near pune Station is best hotel to experience luxurious stay in pune city. Specially housekeeping staff are very polite and dedicated about there job. Whether it is a 3 am at night or 2 pm afternoon you will get same experience in terms of housekeeping service. Special thanks to \" Mrs. Renuka\" madam for her kind & calm behavior. You will feel like a home.\n\nKeep up same enthusiasm team !!",
    "Visited this lovely hotel in Dec 19 with my family. The hotel is located bang opposite Pune railway station withing walking distance. I've stayed at several Lemon Tree properties in the past and this one like the rest doesn't fail to impress. Clean rooms with great hospitality is what makes the brand unique. They have a variety of add ons like late/early check ins etc. Don't expect this brand to be in the league of a Westin or a Marriott. However all said and done this place is a bang for one's buck. We got an upgrade to a higher floor and the rooms were way better than what we asked for. Since we are on a Modified American Plan, we opted for dinner at their Coffee shop called Citrus. Honestly the dinner was very mediocre , however for the price that we paid, it was worth it. Breakfast on the contrary was a treat. The staff were all extremely hospitable and made the kids feel at home. The property has a full fledged gym and an open air swimming pool on the lower floor. They have a lounge has well that offers a liquid buffet (unlimited alcohol at a fixed price). Since the property is so centrally located, travelling is very convenient. The kids really enjoyed their stay and I'm guessing that says it all.",
    "I can't begin to elaborate at the number of things that are wrong with this place, so lets begin:\n\n1) Firstly the AC just doesn't work, when you call them about it they say they are mandated by the government to keep the AC above 24 deg. However they have been keeping the AC at 30 so you can imagine the heat especially without opening windows or any sort of ventilation. Since we stayed for 8 days, we had to fight and complain just in order to get the AC at a livable temperature. It didn't end there, everyday we would go out the AC would be back to its normal heat and we would have to repeat the fighting and complaining every single night.\n\n2) We had booked a suite for the last day for the married couple to spend their first night. However 2 3 days before that. I get a call from the manager saying that we are closing the hotel from tomorrow so we are moving you to a lemon tree property in another part of the town. I told him I don't want to move to another part of the town there's a reason I booked this location. I told him I'll make some alternate arrangements for my remaining 3 days as well as the suite booked for the married couple. I went through the day and did make all alternate arrangements at a nearby hotel. When I go back here and told the front desk that I need a refund since you'll are closing the hotel and Im moving out. They said no now we are not closing the hotel and we cannot give you a refund. So here I am having paid for 2 hotels because of their sheer stupidity.\n\n3) Thirdly this is not a very important point but all things out together it does add up to the irritation of staying here. I've stayed at multiple hotels at various budget ranges, but this is the first hotel that seems to charge everything I mean everything. I asked for 2 plates and cutlery they charges me 75 Rs. Plus tax. I asked for a dental kit, I mean a dental kit is available at all hotels as an amenity, they charged me 27 Rs plus taxes for it.\n\nSo guys please avoid staying here. I'm definitely not coming back here ever again."
]
product_category="household"
print(upload_to_gcs.upload(reviews,product_category))

